export const countries = [
  { name: "Afghanistan", code: "+93", abbr: "AF" },
  { name: "Albania", code: "+355", abbr: "AL" },
  { name: "Algeria", code: "+213", abbr: "DZ" },
  { name: "American Samoa", code: "+684", abbr: "AS" },
  { name: "Andorra", code: "+376", abbr: "AD" },
  { name: "Angola", code: "+244", abbr: "AO" },
  { name: "Anguilla", code: "+264", abbr: "AI" },
  { name: "Antarctica", code: "+672", abbr: "AQ" },
  { name: "Antigua and Barbuda", code: "+268", abbr: "AG" },
  { name: "Argentina", code: "+54", abbr: "AR" },
  { name: "Armenia", code: "+374", abbr: "AM" },
  { name: "Aruba", code: "+297", abbr: "AW" },
  { name: "Australia", code: "+61", abbr: "AU" },
  { name: "Austria", code: "+43", abbr: "AT" },
  { name: "Azerbaijan", code: "+994", abbr: "AZ" },
  { name: "Bahamas", code: "+242", abbr: "BS" },
  { name: "Bahrain", code: "+973", abbr: "BH" },
  { name: "Bangladesh", code: "+880", abbr: "BD" },
  { name: "Barbados", code: "+246", abbr: "BB" },
  { name: "Belarus", code: "+375", abbr: "BY" },
  { name: "Belgium", code: "+32", abbr: "BE" },
  { name: "Belize", code: "+501", abbr: "BZ" },
  { name: "Benin", code: "+229", abbr: "BJ" },
  { name: "Bermuda", code: "+441", abbr: "BM" },
  { name: "Bhutan", code: "+975", abbr: "BT" },
  { name: "Bolivia", code: "+591", abbr: "BO" },
  { name: "Bosnia and Herzegovina", code: "+387", abbr: "BA" },
  { name: "Botswana", code: "+267", abbr: "BW" },
  { name: "Brazil", code: "+55", abbr: "BR" },
  { name: "British Indian Ocean Territory", code: "+246", abbr: "IO" },
  { name: "British Virgin Islands", code: "+284", abbr: "VG" },
  { name: "Brunei", code: "+673", abbr: "BN" },
  { name: "Bulgaria", code: "+359", abbr: "BG" },
  { name: "Burkina Faso", code: "+226", abbr: "BF" },
  { name: "Burundi", code: "+257", abbr: "BI" },
  { name: "Cambodia", code: "+855", abbr: "KH" },
  { name: "Cameroon", code: "+237", abbr: "CM" },
  { name: "Canada", code: "+1", abbr: "CA" },
  { name: "Cape Verde", code: "+238", abbr: "CV" },
  { name: "Cayman Islands", code: "+345", abbr: "KY" },
  { name: "Central African Republic", code: "+236", abbr: "CF" },
  { name: "Chad", code: "+235", abbr: "TD" },
  { name: "Chile", code: "+56", abbr: "CL" },
  { name: "China", code: "+86", abbr: "CN" },
  { name: "Christmas Island", code: "+61", abbr: "CX" },
  { name: "Cocos Islands", code: "+61", abbr: "CC" },
  { name: "Colombia", code: "+57", abbr: "CO" },
  { name: "Comoros", code: "+269", abbr: "KM" },
  { name: "Cook Islands", code: "+682", abbr: "CK" },
  { name: "Costa Rica", code: "+506", abbr: "CR" },
  { name: "Croatia", code: "+385", abbr: "HR" },
  { name: "Cuba", code: "+53", abbr: "CU" },
  { name: "Curacao", code: "+599", abbr: "CW" },
  { name: "Cyprus", code: "+357", abbr: "CY" },
  { name: "Czech Republic", code: "+420", abbr: "CZ" },
  { name: "Democratic Republic of the Congo", code: "+243", abbr: "CD" },
  { name: "Denmark", code: "+45", abbr: "DK" },
  { name: "Djibouti", code: "+253", abbr: "DJ" },
  { name: "Dominica", code: "+767", abbr: "DM" },
  { name: "Dominican Republic", code: "+809", abbr: "DO" },
  { name: "East Timor", code: "+670", abbr: "TL" },
  { name: "Ecuador", code: "+593", abbr: "EC" },
  { name: "Egypt", code: "+20", abbr: "EG" },
  { name: "El Salvador", code: "+503", abbr: "SV" },
  { name: "Equatorial Guinea", code: "+240", abbr: "GQ" },
  { name: "Eritrea", code: "+291", abbr: "ER" },
  { name: "Estonia", code: "+372", abbr: "EE" },
  { name: "Ethiopia", code: "+251", abbr: "ET" },
  { name: "Falkland Islands", code: "+500", abbr: "FK" },
  { name: "Faroe Islands", code: "+298", abbr: "FO" },
  { name: "Fiji", code: "+679", abbr: "FJ" },
  { name: "Finland", code: "+358", abbr: "FI" },
  { name: "France", code: "+33", abbr: "FR" },
  { name: "French Polynesia", code: "+689", abbr: "PF" },
  { name: "Gabon", code: "+241", abbr: "GA" },
  { name: "Gambia", code: "+220", abbr: "GM" },
  { name: "Georgia", code: "+995", abbr: "GE" },
  { name: "Germany", code: "+49", abbr: "DE" },
  { name: "Ghana", code: "+233", abbr: "GH" },
  { name: "Gibraltar", code: "+350", abbr: "GI" },
  { name: "Greece", code: "+30", abbr: "GR" },
  { name: "Greenland", code: "+299", abbr: "GL" },
  { name: "Grenada", code: "+473", abbr: "GD" },
  { name: "Guam", code: "+671", abbr: "GU" },
  { name: "Guatemala", code: "+502", abbr: "GT" },
  { name: "Guernsey", code: "+44-1481", abbr: "GG" },
  { name: "Guinea", code: "+224", abbr: "GN" },
  { name: "Guinea-Bissau", code: "+245", abbr: "GW" },
  { name: "Guyana", code: "+592", abbr: "GY" },
  { name: "Haiti", code: "+509", abbr: "HT" },
  { name: "Honduras", code: "+504", abbr: "HN" },
  { name: "Hong Kong", code: "+852", abbr: "HK" },
  { name: "Hungary", code: "+36", abbr: "HU" },
  { name: "Iceland", code: "+354", abbr: "IS" },
  { name: "India", code: "+91", abbr: "IN" },
  { name: "Indonesia", code: "+62", abbr: "ID" },
  { name: "Iran", code: "+98", abbr: "IR" },
  { name: "Iraq", code: "+964", abbr: "IQ" },
  { name: "Ireland", code: "+353", abbr: "IE" },
  { name: "Isle of Man", code: "+44-1624", abbr: "IM" },
  { name: "Israel", code: "+972", abbr: "IL" },
  { name: "Italy", code: "+39", abbr: "IT" },
  { name: "Ivory Coast", code: "+225", abbr: "CI" },
  { name: "Jamaica", code: "+876", abbr: "JM" },
  { name: "Japan", code: "+81", abbr: "JP" },
  { name: "Jersey", code: "+44-1534", abbr: "JE" },
  { name: "Jordan", code: "+962", abbr: "JO" },
  { name: "Kazakhstan", code: "+7", abbr: "KZ" },
  { name: "Kenya", code: "+254", abbr: "KE" },
  { name: "Kiribati", code: "+686", abbr: "KI" },
  { name: "Kosovo", code: "+383", abbr: "XK" },
  { name: "Kuwait", code: "+965", abbr: "KW" },
  { name: "Kyrgyzstan", code: "+996", abbr: "KG" },
  { name: "Laos", code: "+856", abbr: "LA" },
  { name: "Latvia", code: "+371", abbr: "LV" },
  { name: "Lebanon", code: "+961", abbr: "LB" },
  { name: "Lesotho", code: "+266", abbr: "LS" },
  { name: "Liberia", code: "+231", abbr: "LR" },
  { name: "Libya", code: "+218", abbr: "LY" },
  { name: "Liechtenstein", code: "+423", abbr: "LI" },
  { name: "Lithuania", code: "+370", abbr: "LT" },
  { name: "Luxembourg", code: "+352", abbr: "LU" },
  { name: "Macau", code: "+853", abbr: "MO" },
  { name: "Macedonia", code: "+389", abbr: "MK" },
  { name: "Madagascar", code: "+261", abbr: "MG" },
  { name: "Malawi", code: "+265", abbr: "MW" },
  { name: "Malaysia", code: "+60", abbr: "MY" },
  { name: "Maldives", code: "+960", abbr: "MV" },
  { name: "Mali", code: "+223", abbr: "ML" },
  { name: "Malta", code: "+356", abbr: "MT" },
  { name: "Marshall Islands", code: "+692", abbr: "MH" },
  { name: "Mauritania", code: "+222", abbr: "MR" },
  { name: "Mauritius", code: "+230", abbr: "MU" },
  { name: "Mayotte", code: "+262", abbr: "YT" },
  { name: "Mexico", code: "+52", abbr: "MX" },
  { name: "Micronesia", code: "+691", abbr: "FM" },
  { name: "Moldova", code: "+373", abbr: "MD" },
  { name: "Monaco", code: "+377", abbr: "MC" },
  { name: "Mongolia", code: "+976", abbr: "MN" },
  { name: "Montenegro", code: "+382", abbr: "ME" },
  { name: "Montserrat", code: "+664", abbr: "MS" },
  { name: "Morocco", code: "+212", abbr: "MA" },
  { name: "Mozambique", code: "+258", abbr: "MZ" },
  { name: "Myanmar", code: "+95", abbr: "MM" },
  { name: "Namibia", code: "+264", abbr: "NA" },
  { name: "Nauru", code: "+674", abbr: "NR" },
  { name: "Nepal", code: "+977", abbr: "NP" },
  { name: "Netherlands", code: "+31", abbr: "NL" },
  { name: "Netherlands Antilles", code: "+599", abbr: "AN" },
  { name: "New Caledonia", code: "+687", abbr: "NC" },
  { name: "New Zealand", code: "+64", abbr: "NZ" },
  { name: "Nicaragua", code: "+505", abbr: "NI" },
  { name: "Niger", code: "+227", abbr: "NE" },
  { name: "Nigeria", code: "+234", abbr: "NG" },
  { name: "Niue", code: "+683", abbr: "NU" },
  { name: "North Korea", code: "+850", abbr: "KP" },
  { name: "Northern Mariana Islands", code: "+670", abbr: "MP" },
  { name: "Norway", code: "+47", abbr: "NO" },
  { name: "Oman", code: "+968", abbr: "OM" },
  { name: "Pakistan", code: "+92", abbr: "PK" },
  { name: "Palau", code: "+680", abbr: "PW" },
  { name: "Palestine", code: "+970", abbr: "PS" },
  { name: "Panama", code: "+507", abbr: "PA" },
  { name: "Papua New Guinea", code: "+675", abbr: "PG" },
  { name: "Paraguay", code: "+595", abbr: "PY" },
  { name: "Peru", code: "+51", abbr: "PE" },
  { name: "Philippines", code: "+63", abbr: "PH" },
  { name: "Pitcairn", code: "+64", abbr: "PN" },
  { name: "Poland", code: "+48", abbr: "PL" },
  { name: "Portugal", code: "+351", abbr: "PT" },
  { name: "Puerto Rico", code: "+787", abbr: "PR" },
  { name: "Qatar", code: "+974", abbr: "QA" },
  { name: "Republic of the Congo", code: "+242", abbr: "CG" },
  { name: "Reunion", code: "+262", abbr: "RE" },
  { name: "Romania", code: "+40", abbr: "RO" },
  { name: "Russia", code: "+7", abbr: "RU" },
  { name: "Rwanda", code: "+250", abbr: "RW" },
  { name: "Saint Barthelemy", code: "+590", abbr: "BL" },
  { name: "Saint Helena", code: "+290", abbr: "SH" },
  { name: "Saint Kitts and Nevis", code: "+869", abbr: "KN" },
  { name: "Saint Lucia", code: "+758", abbr: "LC" },
  { name: "Saint Martin", code: "+590", abbr: "MF" },
  { name: "Saint Pierre and Miquelon", code: "+508", abbr: "PM" },
  { name: "Saint Vincent and the Grenadines", code: "+784", abbr: "VC" },
  { name: "Samoa", code: "+685", abbr: "WS" },
  { name: "San Marino", code: "+378", abbr: "SM" },
  { name: "Sao Tome and Principe", code: "+239", abbr: "ST" },
  { name: "Saudi Arabia", code: "+966", abbr: "SA" },
  { name: "Senegal", code: "+221", abbr: "SN" },
  { name: "Serbia", code: "+381", abbr: "RS" },
  { name: "Seychelles", code: "+248", abbr: "SC" },
  { name: "Sierra Leone", code: "+232", abbr: "SL" },
  { name: "Singapore", code: "+65", abbr: "SG" },
  { name: "Sint Maarten", code: "+721", abbr: "SX" },
  { name: "Slovakia", code: "+421", abbr: "SK" },
  { name: "Slovenia", code: "+386", abbr: "SI" },
  { name: "Solomon Islands", code: "+677", abbr: "SB" },
  { name: "Somalia", code: "+252", abbr: "SO" },
  { name: "South Africa", code: "+27", abbr: "ZA" },
  { name: "South Korea", code: "+82", abbr: "KR" },
  { name: "South Sudan", code: "+211", abbr: "SS" },
  { name: "Spain", code: "+34", abbr: "ES" },
  { name: "Sri Lanka", code: "+94", abbr: "LK" },
  { name: "Sudan", code: "+249", abbr: "SD" },
  { name: "Suriname", code: "+597", abbr: "SR" },
  { name: "Svalbard and Jan Mayen", code: "+47", abbr: "SJ" },
  { name: "Swaziland", code: "+268", abbr: "SZ" },
  { name: "Sweden", code: "+46", abbr: "SE" },
  { name: "Switzerland", code: "+41", abbr: "CH" },
  { name: "Syria", code: "+963", abbr: "SY" },
  { name: "Taiwan", code: "+886", abbr: "TW" },
  { name: "Tajikistan", code: "+992", abbr: "TJ" },
  { name: "Tanzania", code: "+255", abbr: "TZ" },
  { name: "Thailand", code: "+66", abbr: "TH" },
  { name: "Togo", code: "+228", abbr: "TG" },
  { name: "Tokelau", code: "+690", abbr: "TK" },
  { name: "Tonga", code: "+676", abbr: "TO" },
  { name: "Trinidad and Tobago", code: "+868", abbr: "TT" },
  { name: "Tunisia", code: "+216", abbr: "TN" },
  { name: "Turkey", code: "+90", abbr: "TR" },
  { name: "Turkmenistan", code: "+993", abbr: "TM" },
  { name: "Turks and Caicos Islands", code: "+649", abbr: "TC" },
  { name: "Tuvalu", code: "+688", abbr: "TV" },
  { name: "U.S. Virgin Islands", code: "+340", abbr: "VI" },
  { name: "Uganda", code: "+256", abbr: "UG" },
  { name: "Ukraine", code: "+380", abbr: "UA" },
  { name: "United Arab Emirates", code: "+971", abbr: "AE" },
  { name: "United Kingdom", code: "+44", abbr: "GB" },
  { name: "United States", code: "+1", abbr: "US" },
  { name: "Uruguay", code: "+598", abbr: "UY" },
  { name: "Uzbekistan", code: "+998", abbr: "UZ" },
  { name: "Vanuatu", code: "+678", abbr: "VU" },
  { name: "Vatican", code: "+379", abbr: "VA" },
  { name: "Venezuela", code: "+58", abbr: "VE" },
  { name: "Vietnam", code: "+84", abbr: "VN" },
  { name: "Wallis and Futuna", code: "+681", abbr: "WF" },
  { name: "Western Sahara", code: "+212", abbr: "EH" },
  { name: "Yemen", code: "+967", abbr: "YE" },
  { name: "Zambia", code: "+260", abbr: "ZM" },
  { name: "Zimbabwe", code: "+263", abbr: "ZW" },
];
